name: Build Windows
on:
  workflow_call:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0"
        type: string
      release-upload-url:
        description: "Release upload URL"
        required: true
        type: string
      app-name:
        description: "Application name"
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    env:
      RELEASE_PATH: build/windows/runner/Release
      APPNAME: ${{ inputs.app-name }}
      VERSION: ${{ inputs.version }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.4.0

      - name: Build Windows app
        run: flutter build windows --release

      - name: Run Installers/installer.iss Inno script
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" /dversion=${{env.VERSION}} "Installers/installer.iss"
        shell: cmd

      - name: upload setup to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ inputs.release-upload-url }}
          asset_path: Installers/${{env.APPNAME}}-setup-windows.exe
          asset_name: ${{env.APPNAME}}-setup-windows.exe
          asset_content_type: application/x-msdownload

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: ${{ env.APPNAME }}-windows.zip
          directory: ${{ env.RELEASE_PATH }}

      - name: upload zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ inputs.release-upload-url }}
          asset_path: ${{env.RELEASE_PATH}}/${{env.APPNAME}}-windows.zip
          asset_name: ${{env.APPNAME}}-windows.zip
          asset_content_type: application/zip
